# Generated by Django 2.1.3 on 2018-11-23 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181123_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('Horrible', 'Horrible'), ('Bad', 'Bad'), ('Okay', 'Okay'), ('Great', 'Great'), ('Awesome', 'Awesome')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 20, 30, 4, 538169, tzinfo=utc), verbose_name='date published'),
        ),
    ]
